export { Header } from "./Header"
export { Team } from "./Team"
export { About } from "./About"
export { Portfolio } from "./Portfolio"
export { Contact } from "./Contact"
export { Footer } from "./Footer"
